// angular_project/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../services/user.service';
import { UserDTO } from '../model/user.dto';
import { ResponseDTO } from '../model/response.dto';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {

  constructor(private router: Router, private userService: UserService) { }

  email: string;
  password: string;


  navigateToHome(user_id: number) {
    this.router.navigate(['home', user_id]);
  }


  login() {
    if (this.email == null || this.password == null || this.email == '' || this.password == '') {
      alert('Preencha todos os campos');
    } else {
      let user: UserDTO = new UserDTO(this.email, this.password);
      this.userService.login(user).subscribe((response: ResponseDTO) => {
        if (response.auth) {
          this.navigateToHome(response.id);
        } else{
          alert("Ocorreu um erro ao fazer login, verifique os dados e tente novamente");
        }
      });
    }
  }


  goToCadastro() {
    this.router.navigate(['cadastro']);
  }

}

<div class="geral">
  <div class="form">
      <h1 class="title">Login</h1>
      <input
          [(ngModel)]="email"
          type="text"
          name="email"
          placeholder="Email"
          class="register-input"
      />
      <input
          [(ngModel)]="password"
          type="password"
          name="password"
          placeholder="Senha"
          class="register-input"
      />
      <div class="buttons">
          <button class="buttonLogin" (click)="login()">Entrar</button>
          <button class="buttonRegister" (click)="goToCadastro()">Cadastrar</button>
      </div>
  </div>
</div>

// react_project/front/src/pages/Login/index.js
import React, { useState } from "react";
import Axios from "axios";

import "./login.css";

export default function Login() {
    const [email, setEmail] = useState();
    const [password, setPassword] = useState();
    
    function navigateToHome(id){
        window.location.href = '/home/' + Number.parseInt(id);
    }

    const doLogin = () => {
        if (email == null || password == null) {
            alert("Preencha todos os campos");
        } else {
            Axios.patch("http://localhost:3001/login", {
                email: email,
                password: password,
            }).then((response) => {
                if(response.data.auth){
                    navigateToHome(response.data.id);
                }else{
                    alert("Senha ou email incorretos");
                }
            });
        }
    };

    
    return (
        <div className="geral">
            <div className="form">
                <h1 className="title">Login</h1>
                <input
                    type="text"
                    name="email"
                    placeholder="Email"
                    className="register-input"
                    onChange={(e) => {
                        setEmail(e.target.value);
                    }}
                />
                <input
                    type="password"
                    name="password"
                    placeholder="Senha"
                    className="register-input"
                    onChange={(e) => {
                        setPassword(e.target.value);
                    }}
                />
                <div className="buttons">
                    <button className="buttonLogin" onClick={doLogin}>Entrar</button>
                    <button className="buttonRegister" onClick={() => window.location.href = '/register'}>Cadastrar</button>
                </div>
            </div>
        </div>
    );
}
